#!/bin/sh
DIR="`realpath "$0"`"
CHEZ=$(cygpath "C:\msys64\home\joshua.hillerup\ChezScheme\ta6nt\bin\ta6nt/scheme.exe")
export PATH="`dirname "$DIR"`/"idris2-fsharp_app":$PATH"
"$CHEZ" --script "$(dirname "$DIR")/idris2-fsharp_app\idris2-fsharp.so" "$@"
